name: MacOS latest C/C++ (no features)

on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        configure_args:
          - >-
            --enable-html-matrix=no
            --enable-parallel=no
            --enable-pytest=no
            --enable-shared=yes
            --enable-silent-rules
            --enable-static=yes
            --enable-usrp=no
            --enable-winradio=no
            --with-cxx-binding=no
            --with-indi=no
            --with-libusb=no
            --with-lua-binding=no
            --with-perl-binding=no
            --with-python-binding=no
            --with-readline=no
            --with-tcl-binding=no
            --with-xml-support=no

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies on MacOS
      run: |
        brew install autoconf
        brew install automake
        brew install libnova
        brew install libtool
        brew install grep
        brew install swig
        brew install tcl-tk
    - name: bootstrap
      run: |
        pwd
        ./bootstrap
    - name: Suppress -Winitializer-overrides on MacOS
      run: |
        export CFLAGS="$CFLAGS -Wno-initializer-overrides"
        export CXXFLAGS="$CXXFLAGS -Wno-initializer-overrides"
    - name: configure on MacOS
      run: ./configure ${{ matrix.configure_args }} --with-indi=detect --without-lua-binding PYTHON=/opt/homebrew/bin/python3
    - name: make distcheck
      run: make distcheck V=0 --no-print-directory AM_DISTCHECK_CONFIGURE_FLAGS="${{ matrix.configure_args }} --with-indi=detect --without-perl-binding --without-lua-binding --without-tcl-binding PYTHON=/opt/homebrew/bin/python3"
    - name: 'tar files'
      run: tar -cvf macos_latest_no_features.tar $(pwd)
    - name: 'Upload Build Artifact'
      uses: actions/upload-artifact@v4.6.2
      with:
        name: 'Macos_latest_no_features'
        path: macos_latest_no_features.tar
